//#pragma once

// NAGISA_BUILD_LIB_CONFIG_ENABLE_INLINE
// NAGISA_BUILD_LIB_CONFIG_VERSION

#if NAGISA_BUILD_LIB_CONFIG_ENABLE_INLINE
#
#	define NAGISA_BUILD_LIB_INLINE_MODIFIER inline
#
#else
#
#	define NAGISA_BUILD_LIB_INLINE_MODIFIER
#
#endif

#ifdef NAGISA_BUILD_LIB_CONFIG_VERSION
#
#	define NAGISA_BUILD_LIB_VERSION NAGISA_BUILD_LIB_CONFIG_VERSION
#
#else
#
#	define NAGISA_BUILD_LIB_VERSION (0,0,0)
#
#endif
