//#pragma once

#undef NGS_BUILD_LIB_BEGIN
#undef NGS_BUILD_LIB_END

#undef NGS_BUILD_LIB_CONFIG_ENABLE_INLINE
#undef NGS_BUILD_LIB_NAME

#undef NGS_BUILD_LIB_CONFIG_VERSION
#undef NGS_BUILD_LIB_VERSION

#undef NGS_BUILD_LIB_CONFIG_DISABLE_NGS_ROOT_NS